name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: pip install -r requirements-dev.txt -r requirements.txt
      - name: Run tests
        run: pytest -vv --cov=wac/ --cov-report term-missing tests/
